server:
  port: 8080

service:
  helloHost: localhost
  #helloHost: ${HELLO_SERVICE_HOST}

# new

opentracing:
  jaeger:
    http-sender:
      #url: http://localhost:14268/api/traces
      url: http://jaeger-production-collector.tracing-system.svc.cluster.local:4318/v1/traces
    #enable-b3-propagation: true
spring:
  application:
    name: channel-service
