server:
  port: 8888

opentracing:
  jaeger:
    http-sender:
      #url: http://localhost:14268/api/traces
      url: http://jaeger-production-collector.tracing-system.svc.cluster.local:4318/v1/traces
    #enable-b3-propagation: true
spring:
  application:
    name: account-service

logging:
  level:
    io.opentracing: DEBUG
